name: Deploy Azure Function (Python)

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies (sanity check)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # ✨ Add this step
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify login
        run: az account show

      # ✨ Change this step (remove publish-profile)
      - name: Azure Functions - Deploy
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '.'
